spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

  cloud:
    stream:
      bindings:
        cancelOrderCompensate-in-0:
          destination: order
          group: order

      rabbit:
        bindings:
          cancelOrderCompensate:
            consumer:
              bindQueue: false
              declareExchange: false
              queueNameGroupOnly: false
