spring:
  rabbitmq:
    username: root
    password: root
    host: localhost
    port: 5672

  cloud:
    stream:
      bindings:
        cancelOrderCompensate-in-0:
          destination: cancelOrderCompensate
        cancelOrder-out-0:
          destination: order

#
#      rabbit:
#        bindings:
#          cancelOrder:
#            consumer:
#              bindQueue: false
#              declareExchange: false
#              queueNameGroupOnly: false
