spring:
  rabbitmq:
    username: root
    password: root
    host: localhost
    port: 5672

  cloud:
    stream:
      bindings:
        paymentProcessor-in-0:
          destination: order
        paymentProcessor-out-0:
          destination: cancelOrderCompensate



#      rabbit:
#        bindings:
#          paymentProcessor:
#            consumer:
#              bindQueue: false
#              declareExchange: false
#              queueNameGroupOnly: false
